[database]
data_store = "clickhouse://default:@clickhouse:8123/default"
cache_store = "redis://redis:6379/0"

[master]
port = 8086
host = "0.0.0.0"
http_port = 8088
http_host = "0.0.0.0"

[recommend]
cache_size = 5000
cache_expire = "168h"
fit_jobs = 4
n_neighbors = 10

