[database]
data_store = "mongodb://root:password@127.0.0.1:27017/gorse?authSource=admin&connect=direct"
cache_store = "redis://127.0.0.1:6379/0"

[master]
port = 8086
host = "0.0.0.0"
http_port = 8088
http_host = "0.0.0.0"

[recommend]
cache_size = 5000
cache_expire = "168h"
fit_jobs = 4
n_neighbors = 10
